import { AppProvider } from '@/components/AppProvider';
import Header from '@/components/layouts/Header';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ClientOnly from '@/components/ClientOnly';
import Footer from '@/components/layouts/Footer';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen overflow-x-hidden `}
            >
                <ClientOnly>
                    <AppProvider>
                        <Header />
                        {children}
                        <Footer />
                    </AppProvider>
                </ClientOnly>
            </body>
        </html>
    );
}
